#https://github.com/marketplace/actions/run-salesforce-code-analyzer
name: Salesforce Code Analyzer
on:
  pull_request:
    types: [opened, synchronize, reopened] # run only on these PR events
    branches:
      - dev # only when PR is raised against dev branch
jobs:
  salesforce-code-analyzer:
    permissions:
      pull-requests: write # Grants permission to create a pull request review. Only necessary if running against pull requests.
      contents: read # Grants permission to check out the repository. Only necessary for private repos.
      actions: read # Grants permission to read the in-progress actions. Only necessary for private repos.
    runs-on: ubuntu-latest
    steps:
      - name: Check out files
        uses: actions/checkout@v4

      # PREREQUISITES - Only needed if the runner doesn't already satisfy these requirements.
      - name: Ensure node v20.9.0 or greater
        uses: actions/setup-node@v4
        with:
          node-version: '>=20.9.0'
      - name: Ensure java v11 or greater
        uses: actions/setup-java@v4
        with:
          java-version: '>=11'
          distribution: 'zulu'
      - name: Ensure python v3.10 or greater
        uses: actions/setup-python@v5
        with:
          python-version: '>=3.10'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Install Latest Salesforce Code Analyzer CLI Plugin
        run: sf plugins install code-analyzer@latest

      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v2
        with:
          run-arguments: --workspace . --view detail --output-file sfca_results.html --output-file sfca_results.json
          results-artifact-name: salesforce-code-analyzer-results
          github-token: ${{ github.token }}

      # sev1- Critical Severity, sev2 - High, sev3 - Medium, sev4 - Low, sev5 - Info
      - name: Check the Outputs to Determine Whether to Fail
        if: |
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-sev2-violations > 0 ||
          steps.run-code-analyzer.outputs.num-sev3-violations > 0
        run: exit 1