#https://github.com/marketplace/actions/run-salesforce-code-analyzer
name: Salesforce Code Analyzer
on:
  pull_request:
    types: [opened, synchronize, reopened] # run only on these PR events
    branches:
      - dev # only when PR is raised against dev branch
jobs:
  salesforce-code-analyzer:
    permissions:
      pull-requests: write # Grants permission to create a pull request review. Only necessary if running against pull requests.
      contents: read # Grants permission to check out the repository. Only necessary for private repos.
      actions: read # Grants permission to read the in-progress actions. Only necessary for private repos.
    runs-on: ubuntu-latest
    steps:
      - name: Check out files
        uses: actions/checkout@v4

      # PREREQUISITES - Only needed if the runner doesn't already satisfy these requirements.
      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Install Latest Salesforce Code Analyzer CLI Plugin
        run: sf plugins install code-analyzer@latest

      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v2
        with:
          run-arguments: --workspace . --view detail --output-file sfca_results.html --output-file sfca_results.json
          results-artifact-name: salesforce-code-analyzer-results
          github-token: ${{ github.token }}
        
      - name: Upload Analyzer Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-analyzer-report
          path: sfca_results.html

      - name: Comment Report Link on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Code Analyzer Report
          message: |
            Salesforce Code Analyzer finished.
            [Here is the Code Analyzer Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)

      # sev1- Critical Severity, sev2 - High, sev3 - Medium, sev4 - Low, sev5 - Info
      - name: Check the Outputs to Determine Whether to Fail
        if: |
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-sev2-violations > 0 ||
          steps.run-code-analyzer.outputs.num-sev3-violations > 0
        run: exit 1
