name: Salesforce PR Validation

on:
  workflow_run:
    workflows: ["Salesforce Code Analyzer"]
    types: [completed]

# Environment variables
env:
  SF_USE_GENERIC_UNIX_KEYCHAIN: true

jobs:
  validate-deployment: # run only for feature branches and on success of code analyzer
    if: >
      startsWith(github.event.workflow_run.head_branch, 'feature/') &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # PREREQUISITES - Only needed if the runner doesn't already satisfy these requirements.
      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      # Create JWT key file from secret
      - name: Create JWT Key File
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > jwt-key.txt
          chmod 600 jwt-key.txt

      # Authenticate to Salesforce using JWT
      - name: Authenticate to Salesforce
        run: |
          sf org login jwt \
            --client-id ${{ secrets.SF_CLIENT_ID }} \
            --jwt-key-file jwt-key.txt \
            --username ${{ secrets.SF_USERNAME }} \
            --instance-url ${{ secrets.SF_INSTANCE_URL }} \
            --alias target-org \
            --set-default

      # Verify authentication
      - name: Verify Authentication
        run: |
          sf org display --target-org target-org
      #Change Repo Root    
      - name: Change to repo root
        run: |
          cd $GITHUB_WORKSPACE

      # Validate Deployment with specified tests
      - name: Validate Deployment with Specified Tests
        run: |
          echo "Reading test classes from TestClass.txt..."
          TESTS=$(cat RunTest.txt | tr '\n' ',' | sed 's/,$//')

          echo "Running validation with tests: $TESTS"

          sf project deploy validate \
            --source-dir force-app/ \
            --test-level RunSpecifiedTests \
            --tests "$TESTS" \
            --wait 10 \
            --target-org target-org
